<?php
  /**
   * Implements hook_form_alter().
   * Extends the User Profile Form with the calendar view
   */
  function pw_profile_extender_form_alter(&$form, &$form_state, $form_id)
  {
    if ($form_id == 'user_profile_form') {
      $form['calendar admin'] = array(
        '#title' => 'My Calendar',
        '#type' => 'markup',
        '#markup' => views_embed_view('calendar', 'calendar_admin_block'),
        '#weight' => 8,
      );
      unset($form["locale"]);
    }
  }

  /**
   * Implements form_views_exposed_form_alter().
   * Adds checkboxes to the alphabetical filter
   */
  function  pw_profile_extender_form_views_exposed_form_alter(&$form, &$form_state, $form_id)
  {
    if ($form['#id'] == 'views-exposed-form-profile-list-rev-grid') {

      //politician overview: change letter select to checkboxes
      $form['field_user_first_letter_lname_value']['#theme'] = 'select_as_checkboxes';

      $form['between_date_filter_op']['#options']['='] = t('Aktive Abgeordnete');
      $form['between_date_filter_op']['#options']['!='] = t('Ausgeschiedene Abgeordnete');
      //krumo($form);
      //$form['between_date_filter_op']['#theme'] = 'select_as_checkboxes';
      //$form['between_date_filter']['#access'] = FALSE;
    }
  }
/*
  function pw_profile_extender_menu_alter(&$items)
  {
     $items['node/add/calendarentry'] = array(
      'title' => t('Add calendar Entry'),
      'desctiption' => 'Add new calendar entry',
      'type' => MENU_LOCAL_TASK,

    );
  }
*/
