<?php
/**
 * @file
 * helper functions for booking form.
 */

/**
 * Implements hook_form_alter()..
 */
function pw_form_booking_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'webform_client_form_10492') {

    // load user
    $user_uuid = $form['submitted']['user_uuid']['#value'];
    $user = entity_uuid_load('user', array($user_uuid), array(), TRUE);
    $user = array_pop($user);

    // fill fields
    if(isset($user->field_user_parliament['und'][0]['tid'])){
      $parliament_uuid = $user->field_user_parliament['und'][0]['tid'];
      $parliament_term = entity_uuid_load('taxonomy_term', array($parliament_uuid), array(), TRUE);
      $parliament = array_pop($parliament_term);
      $form['submitted']['user_parliament']['#value'] = $parliament->name;
    }
    if(isset($user->field_user_constituency['und'][0]['tid'])){
      $constituency_uuid = $user->field_user_constituency['und'][0]['tid'];
      $constituency_term = entity_uuid_load('taxonomy_term', array($constituency_uuid), array(), TRUE);
      $constituency = array_pop($constituency_term);
      $form['submitted']['user_constituency']['#value'] = $constituency->name;
    }
    if(isset($user->field_user_party['und'][0]['tid'])){
      $party_uuid = $user->field_user_party['und'][0]['tid'];
      $party_term = entity_uuid_load('taxonomy_term', array($party_uuid), array(), TRUE);
      $party = array_pop($party_term);
      $form['submitted']['user_party']['#value'] = $party->name;

    }
    if(isset($user->field_user_gender['und'][0]['value'])){
      $form['submitted']['user_prefix']['#value'] = $user->field_user_gender['und'][0]['value'] == 'f'?'mrs':'mr';
    }
    $form['submitted']['user_first_name']['#value'] = $user->field_user_fname['und'][0]['value'];
    $form['submitted']['user_last_name']['#value'] = $user->field_user_lname['und'][0]['value'];
    $form['submitted']['user_email']['#value'] = $user->mail;
    $form['submitted']['user_phone']['#value'] = $user->field_user_phone['und'][0]['value'];
    $form['submitted']['user_address_street']['#value'] = $user->field_user_address['und'][0]['thoroughfare'];
    $form['submitted']['user_address_postal_code']['#value'] = $user->field_user_address['und'][0]['postal_code'];
    $form['submitted']['user_address_city']['#value'] = $user->field_user_address['und'][0]['locality'];
  }
}

/**
 * Implements hook_form_alter()..
 */
function pw_form_booking_webform_submission_presave($node, &$submission){
  if($node->nid == 10492){

    // give user role Premium User if profile extension was booked via direct debit
    global $user;
    $role_premium = 'Premium User';
    $is_politician = array_search('Politician', $user->roles)?true:false;
    $is_candidate = array_search('Politician', $user->roles)?true:false;
    $has_premium = array_search($role_premium, $user->roles)?true:false;
    if($is_politician && $is_candidate && !$has_premium){
      $system_roles = user_roles(true);
      $rid = array_search($role_premium, $system_roles);
      $new_role[$rid] = $role_premium;
      $new_roles = $user->roles + $new_role;
      user_save($user, array('roles' => $new_roles));
    }
  }
}
