<?php

function pw_civiCustomTokens_civicrm_tokens(&$tokens) {

    $tokens['custom_membership'] = array(
        'custom_membership.aktivemitgliedschaften' => 'Mitgliedschaft - Abbuchungsinfo alle aktiven Mitgliedschaften',
    );
}

function pw_civiCustomTokens_civicrm_tokenValues(&$values, $cids, $job = null, $tokens = array(), $context = null) {
    $contacts = implode(',', $cids);

    if (!empty($tokens['custom_membership'])) {

        $dao = &CRM_Core_DAO::executeQuery("
        SELECT    c.id,
                m.id AS membership_id, 
                custom.mandatsreferenz_dauerspende_21 AS mandatsreferenz,
               option_value.label AS zahlungsintervall,
                custom.mitgliedsbeitrag_5 AS beitrag
      FROM civicrm_contact c
      INNER JOIN civicrm_membership m ON c.id = m.contact_id
      INNER JOIN civicrm_value_bankverbindungsdaten_2 custom ON m.id = custom.entity_id
      INNER JOIN civicrm_option_value option_value ON custom.zahlungsintervall_6 = option_value.value
      WHERE c.id IN ($contacts) AND m.status_id IN (1, 2, 5, 8) AND option_value.option_group_id = 68"
        );
        while ($dao->fetch()) {
            $cid = $dao->id;
            if (!empty($dao->mandatsreferenz)) {
                $values[$cid]['custom_membership.aktivemitgliedschaften'] .= 'Mandatsreferenz: ' . $dao->mandatsreferenz . ' ' . $dao->zahlungsintervall . ' ' . $dao->beitrag . ' Euro' . "\r\n";
            } else {
                $values[$cid]['custom_membership.aktivemitgliedschaften'] .= '';
            }
        }
    }
}

