<?php

/**
 * @file
 * Code for the PW Profiles feature. Implements the switch of the user profile view
 * depending on the role of the users whose profile is shown.
 */

/**
 * Implements the switch between standard and premium profile display modes
 * dependant on user role. The assignment can be configured in the admin part of
 * this module.
 * @return type
 */
function pw_profileswitch_user_custom_view() {

  // load user
  $account = _pw_get_current_user();

  // set custom page title
  drupal_set_title(_pw_get_fullname($account));

  // retrieve user roles of the field field_user_roles_for_view_mode_switch:
  $assignedRoles = array();
  foreach ($account->field_user_roles_for_view_mode_s['und'] as $role) {
    $assignedRoles[$role['tid']] = $role['tid'];
  }

  $assignment = variable_get('pw_profileswitch_assignment', array()); // array(roleId => displayModeId)
  foreach ($assignment as $rid => $did) {
    if (array_key_exists($rid, $assignedRoles)) {
      $view_mode = $did;
      break; // "First role wins": We assume role assignments to users to be DISTINCT!
    }
  }

  return user_view($account, $view_mode, $langcode);
}

/**
 * Modify the default page callbacks from user.and user revisions modules to a custom one.
 * This is needed for the display mode switch between standard profiles and premium profiles.
 *
 * @param array $items
 */
function pw_profileswitch_menu_alter(&$items) {
  $items['user/%/revisions/%/view'] = array(
    'page callback' => 'pw_profileswitch_user_custom_view',
    'access callback' => 'user_view_access', // default access callback for users
    'access arguments' => array(1),
  );
  $items['user/%'] = $items['user/%/revisions/%/view'];
  $items['profil/%/archiv/%'] = $items['user/%/revisions/%/view']; // arrays are copied here
  $items['profil/%/archiv/%']['access callback'] = TRUE; // grant anonymous access
  unset($items['profil/%/archiv/%']['access arguments']); // remove conflicting access
}

/**
 * Implementation of hook_menu().
 */
function pw_profileswitch_menu() {
  $items['admin/config/pw/pw_profileswitch/settings'] = array(
    'title' => 'PW Profileswitch settings',
    'description' => 'Connect User Roles with Display Modes.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pw_profileswitch_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pw_profileswitch.admin.inc',
  );
  return $items;
}

