<?php

/*
 * Implements hook_migrate_api(), setting the API level to 2, for
 * parliament migration classes to be recognized by the Migrate module.
 */
function migrate_parliament_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'ParliamentTerm' => array(
        'class_name' => 'ParliamentTermMigration',
        'group_name' => 'parliament',
      ),
    ),
  );
  return $api;
}

/**
 * Implements hook_update_projects_alter().
 */
function migrate_parliament_update_projects_alter(&$projects) {
  unset($projects['migrate_parliament']);
}
