<?php

/*
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function migrate_parliament_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'ParliamentTerm' => array(
        'class_name' => 'ParliamentTermMigration',
        'group_name' => 'parliament',
      ),
    ),
  );
  return $api;
}
