<?php
/**
 * @file
 */

include_once 'webform_confirm_email.admin.inc';
include_once 'webform_confirm_email.inc';

/**
 * Implements hook_webform_submission_delete().
 *
 * Respond to a Webform submission being deleted - if a submission
 * is deleted the hash for the confirmation URL can be deleted too
 *
 * @param $node
 *   The Webform node on which this submission was made.
 * @param $submission
 *   The Webform submission that was just deleted from the database.
 */
function webform_confirm_email_webform_submission_delete($node, $submission) {
  db_delete('webform_confirm_email_code')
    ->condition('nid', $node->nid)
    ->condition('sid', $submission->sid)
    ->execute();

  db_delete('webform_confirm_email_confirmation_emails')
    ->condition('nid', $node->nid)
    ->condition('sid', $submission->sid)
    ->execute();
}

/**
 * Check whether a given email ID is a confirmation or conditional email
 * and return its type.
 *
 * @param $nid
 *   The Webform node ID for which the email type is fetched
 * @param $eid
 *   The Webform email ID for which the email type is fetched
 */
function webform_confirm_email_get_email_type($nid, $eid) {
  return db_query(
    'SELECT email_type '.
    '  FROM {webform_confirm_email} ' .
    '    WHERE nid = :nid ' .
    '    AND   eid = :eid ',
    array(
      ':nid' => (int) $nid,
      ':eid' => (int) $eid,
    )
  )->fetchField();
}

/**
 * generate a hash for a new email submission, or get an existing hash
 *
 * @param $nid
 *   node id of the submitted form
 * @param $sid
 *   submission id of the submitted form
 * @param $email
 *   email address of the submitter; if empty, it's assumed that the submission
 *   has already happened and the webform_confirm_email_code table is searched
 *   for a hash
 */
function webform_confirm_email_generate_key($nid, $sid, $eid, $email = NULL) {
  if (isset($email)) {
    return hash_hmac('md5', serialize(array($nid, $sid, $eid, $email)), drupal_get_private_key());
  }
  else {
    $result = db_query(
      'SELECT code ' .
      '  FROM {webform_confirm_email_code} ' .
      '    WHERE nid = :nid ' .
      '    AND   sid = :sid ' .
      '    AND   eid = :eid ',
      array(
        ':nid' => $nid,
        ':sid' => $sid,
        ':eid' => $eid,
      )
    );
    return $result->fetchField();
  }
}

/**
 * Implements hook_mail_alter().
 * When drupal sends an email this function checks whether there is an entry
 * in the webform_confirm_email table that identifies the email as being a
 * confirmation request or confirmation email.
 * If it's a confirmational mail a hash code is generated, an URL is generated
 * out of the hash and the "%confirm_url" is replaced in the email by this generated
 * confirmation URL.
 * If it's a confirmation email, the email is stopped from being send; This is because
 * after a webform submission the webform module would send all emails that are
 * registered for this form; but we want the confirmation email to be send only when
 * the user uses the confirmation link that is send to him/her in the confirmation request email.
 *
 * @param $message
 */
function webform_confirm_email_mail_alter(&$message) {
  if (!empty($message['params']['node']) && !empty($message['params']['submission'])) {
    $nid = (int) ($message['params']['node']->nid);
    $sid = (int) ($message['params']['submission']->sid);
    $eid = (int) $message['params']['email']['eid'];
    if (   webform_confirm_email_get_email_type($nid, $eid) == WEBFORM_CONFIRM_EMAIL_CONFIRMATION
        && isset($message['params']['webform_confirm_email_confirmation_send']) == FALSE) {
      $obj = array(
        'nid'           => $nid,
        'sid'           => $sid,
        'email_message' => $message,
      );
      $message['send'] = FALSE; // prevents drupal_mail from actually sending the message
      drupal_write_record('webform_confirm_email_confirmation_emails', $obj);
    }
  }
}

/**
 * callback function that is set in hook_menu().
 * This function is called when a user clicks on the confirmation URL that
 * a submitee gets via email after the 1st submission.
 * If the submission code is found the confirmation mail is send and
 * the submission record is removed from the DB
 */
function webform_confirm_email_confirmation($node,
                                            $submission,
                                            $eid,
                                            $code) {

  if (   !empty($code)
      && webform_confirm_email_generate_key($node->nid, $submission->sid, $eid) == $code) {

    db_delete('webform_confirm_email_code')
      ->condition('nid', $node->nid)
      ->condition('sid', $submission->sid)
      ->condition('eid', $eid)
      ->execute();
    db_query(
      'UPDATE {webform_submissions} ' .
      '  SET confirmed = 1 ' .
      '  WHERE nid = :nid ' .
      '  AND   sid = :sid ',
      array(':nid' => $node->nid, ':sid' => $submission->sid)
    );
    $email_messages = db_query(
      'SELECT email_message ' .
      '  FROM {webform_confirm_email_confirmation_emails} ' .
      '    WHERE nid = :nid ' .
      '    AND   sid = :sid ' ,
      array(
        ':nid' => $node->nid,
        ':sid' => $submission->sid,
      )
    )->fetchCol();

    foreach ($email_messages as $email_message) {
      $email_message = unserialize($email_message);
      // Concatenate and wrap the e-mail body.
      if (is_array($email_message['body'])) {
        $email_message['body'] = implode("\n\n", $email_message['body']);
      }

      $email_message['params']['webform_confirm_email_confirmation_send'] = TRUE;

      $email_message = drupal_mail(
        $email_message['module'],
        $email_message['key'],
        $email_message['to'],
        $email_message['language'],
        $email_message['params'],
        $email_message['from'],
        TRUE
      );

      if ($email_message['result'] == FALSE) {
        watchdog(
          'mail',
          'Error sending e-mail (from %from to %to).',
          array(
            '%from' => $email_message['from'],
            '%to'   => $email_message['to']
          ),
          WATCHDOG_ERROR
        );
        drupal_set_message(t(
            'Unable to send e-mail. ' .
            'Please contact the site administrator if the problem persists.'
          ),
          'error'
        );
      }
    }
    $codes_left_to_be_confirmed = db_query(
      'SELECT nid ' .
      '  FROM {webform_confirm_email_code} ' .
      '    WHERE nid = :nid ' .
      '    AND   sid = :sid ' ,
      array(
        ':nid' => $node->nid,
        ':sid' => $submission->sid,
      )
    )->fetchField();
    if ($codes_left_to_be_confirmed == FALSE) {
      db_query(
        'DELETE FROM {webform_confirm_email_confirmation_emails} ' .
        '  WHERE nid = :nid ' .
        '  AND   sid = :sid ' ,
        array(
          ':nid' => $node->nid,
          ':sid' => $submission->sid,
        )
      );
    }
    // call implementations of hook_email_confirmed
    module_invoke_all('webform_confirm_email_email_confirmed', $node, $submission);
    // trigger a rules email confirmed event
    if (module_exists('rules') == TRUE) {
      rules_invoke_event('webform_confirm_email_email_confirmed', $node, $submission);
    }
  }
  $redirect_url = db_query(
    'SELECT redirect_url ' .
    '  FROM {webform_confirm_email} ' .
    '    WHERE nid = :nid ' .
    '    AND   eid = :eid ',
    array(
      ':nid' => $node->nid,
      ':eid' => $eid,
    )
  )->fetchField();

  if ($redirect_url == NULL) {
    if (empty($node->webform['redirect_url']) == TRUE) {
      drupal_not_found();
    }
    elseif (   $node->webform['redirect_url'] == '<confirmation>'
            || $node->webform['redirect_url'] == '<none>') {
      $redirect_url = 'node/' . $node->nid . '/done';
    }
    else {
      $redirect_url = $node->webform['redirect_url'];
    }
  }

  drupal_goto(
    $redirect_url,
    array(
      'query' => array(
        'sid'     => $submission->sid,
        'confirm' => TRUE,
        'token'   => md5($submission->submitted . $submission->sid . drupal_get_private_key()),
      ),
    )
  );
}

/**
 * Implements hook_menu().
 */
function webform_confirm_email_menu() {
  return array(
    'node/%webform_menu/sid/%webform_menu_submission/eid/%/confirm_email/%' => array(
      'title'           => 'Submit email confirmation',
      'load arguments'  => array(1),
      'page callback'   => 'webform_confirm_email_confirmation',
      'page arguments'  => array(1, 3, 5, 7),
      'access callback' => TRUE,
      'type'            => MENU_CALLBACK,
    ),
    'node/%webform_menu/webform/confirmation_request/%webform_menu_email' => array(
      'title'            => t('Edit confirmation request e-mail settings'),
      'load arguments'   => array(1),
      'page callback'    => 'webform_confirm_email_confirmation_request_email_edit',
      'page arguments'   => array(1, 4),
      'access callback'  => 'node_access',
      'access arguments' => array('update', 1),
      'type'             => MENU_CALLBACK,
    ),
    'node/%webform_menu/webform/confirmation_request/%webform_menu_email/delete' => array(
      'title'            => t('Delete a confirmation request e-mail'),
      'load arguments'   => array(1),
      'page callback'    => 'webform_confirm_email_delete',
      'page arguments'   => array(1, 4),
      'access callback'  => 'node_access',
      'access arguments' => array('update', 1),
      'type'             => MENU_CALLBACK,
    ),
    'node/%webform_menu/webform/confirmation/%webform_menu_email' => array(
      'title'            => t('Edit confirmation e-mail settings'),
      'load arguments'   => array(1),
      'page callback'    => 'webform_confirm_email_confirmation_email_edit',
      'page arguments'   => array(1, 4),
      'access callback'  => 'node_access',
      'access arguments' => array('update', 1),
      'type'             => MENU_CALLBACK,
    ),
    'node/%webform_menu/webform/confirmation/%webform_menu_email/delete' => array(
      'title'            => t('Delete a confirmation e-mail'),
      'load arguments'   => array(1),
      'page callback'    => 'webform_confirm_email_delete',
      'page arguments'   => array(1, 4),
      'access callback'  => 'node_access',
      'access arguments' => array('update', 1),
      'type'             => MENU_CALLBACK,
    ),
    'node/%webform_menu/webform/confirmation-settings' => array(
      'title'            => t('Confirmation mail settings'),
      'page callback'    => 'drupal_get_form',
      'page arguments'   => array('webform_confirm_email_settings', 1),
      'access callback'  => 'node_access',
      'access arguments' => array('update', 1),
      'weight'           => 2,
      'type'             => MENU_LOCAL_TASK,
    ),
  );
}

/**
 * Implements hook_menu_alter().
 */
function webform_confirm_email_menu_alter(&$items) {
  if (isset($items['node/%webform_menu/webform-results']) == TRUE) {
    $items['node/%webform_menu/webform-results'] = array(
      'title'            => 'Results',
      'page callback'    => 'webform_confirm_email_results_submissions',
      'page arguments'   => array(1, FALSE, '50'),
      'access callback'  => 'webform_results_access',
      'access arguments' => array(1),
      'file'             => drupal_get_path('module', 'webform_confirm_email') . '/webform_confirm_email.report.inc',
      'weight'           => 2,
      'type'             => MENU_LOCAL_TASK,
      'context'          => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    );
    $items['node/%webform_menu/webform-results/submissions'] = array(
      'title'            => 'Submissions',
      'page callback'    => 'webform_confirm_email_results_submissions',
      'page arguments'   => array(1, FALSE, '50'),
      'access callback'  => 'webform_results_access',
      'access arguments' => array(1),
      'file'             => drupal_get_path('module', 'webform_confirm_email') . '/webform_confirm_email.report.inc',
      'weight'           => 4,
      'type'             => MENU_DEFAULT_LOCAL_TASK,
    );
    $items['node/%webform_menu/webform-results/table'] = array(
      'title'            => 'Table',
      'page callback'    => 'webform_confirm_email_results_table',
      'page arguments'   => array(1, '50'),
      'access callback'  => 'webform_results_access',
      'access arguments' => array(1),
      'file'             => drupal_get_path('module', 'webform_confirm_email') . '/webform_confirm_email.report.inc',
      'weight'           => 6,
      'type'             => MENU_LOCAL_TASK,
    );
  }
}

/**
 * Implements hook_token_info_alter().
 */
function webform_confirm_email_token_info_alter(&$data) {
  $data['tokens']['submission']['confirm_url'] = array(
    'name'        => t("Confirmation URL"),
    'description' => t('The URL in the email body generated by webform_confirm_email for the user to click and confirm his/her submissions.'),
  );
}


/**
* Implementation hook_token_info().
*/
function webform_confirm_email_token_info() {
  $info['types']['webform-submission'] = array(
    'name'        => t('Submission'),
    'description' => t('Tokens related to webform submissions.'),
    'needs-data'  => 'submission',
  );

  $info['tokens']['webform-submission']['serial'] = array(
    'name'        => t('Serial number'),
    'description' => t('The serial number of this webform submission.'),
  );
  $info['tokens']['webform-submission']['sid'] = array(
    'name'        => t('Submission ID'),
    'description' => t('The unique indentifier for the webform submission.'),
  );
  $info['tokens']['webform-submission']['date'] = array(
    'name'        => t('Date submitted'),
    'description' => t('The date the webform was submitted.'),
    'type'        => 'date',
  );
  $info['tokens']['webform-submission']['ip-address'] = array(
    'name'        => t('IP address'),
    'description' => t('The IP address that was used when submitting the webform.'),
  );
  $info['tokens']['webform-submission']['user'] = array(
    'name'        => t('Submitter'),
    'description' => t('The user that submitted the webform result.'),
    'type'        => 'user',
  );
  $info['tokens']['webform-submission']['url'] = array(
    'name'        => t('URL'),
    'description' => t("Webform tokens related to the submission's URL."),
    'type'        => 'url',
  );
  $info['tokens']['webform-submission']['edit-url'] = array(
    'name'        => t('Edit URL'),
    'description' => t("Webform tokens related to the submission's Edit URL."),
    'type'        => 'url',
  );

  return $info;
}

/**
 * Implements hook_tokens().
 */
function webform_confirm_email_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  if ($type !== 'submission' && $type !== 'webform-submission' || empty($data['webform-submission'])) {
    return $replacements;
  }

  $submission  = $data['webform-submission'];
  $sanitize    = !empty($options['sanitize']);
  $url_options = array('absolute' => TRUE);
  if (isset($options['language'])) {
    $url_options['language'] = $options['language'];
    $language_code           = $options['language']->language;
  }
  else {
    $language_code = NULL;
  }
  $node = isset($data['node']) ? $data['node'] : node_load($submission->nid);
  if (   $type === 'submission'
      && isset($tokens['confirm_url'])
      && !empty($data['webform-email'])) {
    $nid = (int) ($node->nid);
    $sid = (int) ($submission->sid);
    $eid = (int) $data['webform-email']['eid'];
    if (webform_confirm_email_get_email_type($nid, $eid) == WEBFORM_CONFIRM_EMAIL_CONFIRMATION_REQUEST) {
      $obj = array(
        'nid'   => $nid,
        'sid'   => $sid,
        'eid'   => $eid,
        'email' => $data['webform-email']['email'],
      );
      $obj['code']     = webform_confirm_email_generate_key($nid, $sid, $eid, $obj['email']);
      $obj['datetime'] = REQUEST_TIME;
      $confirm_url = url(
        "node/$nid/sid/$sid/eid/$eid/confirm_email/" . $obj['code'],
        array(
          'absolute' => TRUE,
          'external' => FALSE,
        )
      );

      $result = db_query(
        'SELECT nid ' .
        '  FROM {webform_confirm_email_code} ' .
        '    WHERE nid = :nid ' .
        '    AND   sid = :sid ' .
        '    AND   eid = :eid ' ,
        array(
          ':nid' => $nid,
          ':sid' => $sid,
          ':eid' => $eid,
        )
      )->fetchField();

      if ($result != FALSE) {
        // mail was resend -> update record
        drupal_write_record(
          'webform_confirm_email_code',
          $obj,
          array('nid', 'sid', 'eid')
        );
      }
      else {
        // new mail
        drupal_write_record('webform_confirm_email_code', $obj);
      }

      $replacements['[submission:confirm_url]'] = $confirm_url;
    }
  }
  elseif ($type === 'webform-submission' && !empty($tokens)) {
    foreach ($tokens as $key => $repl_str) {
      switch ($key) {
        case 'serial':
          $replacements[$repl_str] = $submission->serial ? $submission->serial : '';
          break;
        case 'sid':
          $replacements[$repl_str] = $submission->sid ? $submission->sid : '';
          break;
        case 'date':
          $replacements[$repl_str] = format_date($submission->submitted, 'medium', '', NULL, $language_code);
          break;
        case 'ip-address':
          $replacements[$repl_str] = $sanitize ? check_plain($submission->remote_addr) : $submission->remote_addr;
          break;
        case 'user':
          $account                 = user_load($submission->uid);
          $name                    = format_username($account);
          $replacements[$repl_str] = $sanitize ? check_plain($name) : $name;
          break;
        case 'url':
          $replacements[$repl_str] = $submission->sid ? url("node/{$node->nid}/submission/{$submission->sid}", $url_options) : '';
          break;
        case 'edit-url':
          $replacements[$repl_str] = $submission->sid ? url("node/{$node->nid}/submission/{$submission->sid}/edit", $url_options) : '';
          break;
      }
    }
    // Chained token relationships.
    if ($date_tokens = token_find_with_prefix($tokens, 'date')) {
      $replacements += token_generate('date', $date_tokens, array('date' => $submission->submitted), $options);
    }
    if (($user_tokens = token_find_with_prefix($tokens, 'user')) && $account = user_load($submission->uid)) {
      $replacements += token_generate('user', $user_tokens, array('user' => $account), $options);
    }
    if ($submission->sid) {
      if ($url_tokens = token_find_with_prefix($tokens, 'url')) {
        $replacements += token_generate('url', $url_tokens, array('path' => "node/{$node->nid}/submission/{$submission->sid}"), $options);
      }
      if ($url_tokens = token_find_with_prefix($tokens, 'edit-url')) {
        $replacements += token_generate('url', $url_tokens, array('path' => "node/{$node->nid}/submission/{$submission->sid}/edit"), $options);
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_help().
 */
function webform_confirm_email_help($path, $arg) {
  if ($path === 'admin/help#webform_confirm_email') {
   return '<h3>Configuration</h3>
You will only notice it is installed when visiting a webform emails
configuration tab. That is, if your webform is defined on a node with node ID
19, you\'ll find the settings by "http://mydomain.net/node/19/webform/emails".
With webform_confirm_email installed you\'ll see 3 email tables instead of 1,
one table for "standard emails", one for "confirmation request emails" and one
for "confirmation emails".
<br>
<br>
The "standard emails" behave just like normal webform emails, "confirmation
reques emails" are send to users asking them to click on a confirmation link
and "confirmation emails" are send only when the confirmation link was used.
<br>
<br>
The forms for changing the 3 different webform email settings (from address,
from name, to address, to name, ...) is the same as the webform email settings
form.  The only difference is in the 2nd email type, the "confirmation request
email", where you have an added entry in the "Token values" list, here you\'ll
find the %confirm_url token that should be used in confirmation request emails.
This token will be expanded to the confirmation link. So as an example the
content of your "E-mail template" could look like this:
<br>
<br>
"Hallo %value[first_name] %value[last_name],
<br>
<br>
<p style="text-indent:2em;">please visit the link below to confirm your submission.</p>
%confirm_url
<br>
<br>
Thank you!
<br>
<br>
Your petition team"';
  }
}

/**
 * Implements hook_cron().
 */
function webform_confirm_email_cron() {
  // get all node id's that we have to check for expired requests
  $nids_lifetime = db_query(
    'SELECT confirm.nid, confirm.request_lifetime, confirm.delete_submissions ' .
    '  FROM {webform_confirm_email_code} code ' .
    '  INNER JOIN {webform_confirm_email} confirm ' .
    '    ON code.nid = confirm.nid ' .
    '  WHERE confirm.request_lifetime IS NOT NULL ' .
    '  GROUP BY confirm.nid '
    )->fetchAllAssoc('nid');

  if (!empty($nids_lifetime)) {
    foreach ($nids_lifetime as $nid => $settings) {
      $expired_sids = array();
      // calculate the oldets timestamp that is still not expired
      // for this nid;
      $timestamp = REQUEST_TIME - $settings->request_lifetime;
      $expired_sids[$nid] = db_query(
        'SELECT sid ' .
        '  FROM {webform_confirm_email_code} ' .
        '    WHERE nid = :nid ' .
        '    AND   datetime < :oldest ' .
        '  GROUP BY sid ' ,
        array(
          ':nid'    => $nid,
          ':oldest' => $timestamp,
        )
      )->fetchCol();

      if (!empty($expired_sids[$nid])) {
        // delete requests from both tables (webform_confirm_email_code,
        // webform_confirm_email_confirmation_emails) at once via JOIN
        db_query(
          'DELETE code, conf ' .
          '  FROM {webform_confirm_email_code} code ' .
          '  LEFT JOIN {webform_confirm_email_confirmation_emails} conf' .
          '    ON  code.nid = conf.nid ' .
          '    AND code.sid = conf.sid ' .
          '  WHERE code.nid = :nid ' .
          '  AND   code.sid in (:sids) ' ,
          array(
            ':nid'  => $nid,
            ':sids' => $expired_sids[$nid],
          )
        );
      }
      module_invoke_all('webform_confirm_email_request_expired', $expired_sids);
      if ($settings->delete_submissions) {
        require_once drupal_get_path('module', 'webform') . '/includes/webform.submissions.inc';
        $node = node_load($nid);
        foreach ($expired_sids[$nid] as $sid) {
          webform_submission_delete($node, webform_get_submission($nid, $sid));
        }
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function webform_confirm_email_theme() {
  return array(
    'webform_confirm_email_results_submissions' => array(
      'render element' => 'element',
      'template'       => 'templates/webform-confirm-email-results-submissions',
      'file'           => 'webform_confirm_email.report.inc',
    ),
    'webform_confirm_email_results_table' => array(
      'variables' => array(
        'confirmed_form' => NULL,
        'node'           => NULL,
        'components'     => NULL,
        'submissions'    => NULL,
        'total_count'    => NULL,
        'pager_count'    => NULL,
      ),
      'file' => 'webform_confirm_email.report.inc',
    ),
  );
}

/**
 * Implements hook_webform_template_insert().
 */
function webform_confirm_email_webform_template_insert($node, $template) {
  db_query(
    'INSERT INTO {webform_confirm_email} ' .
    '  (nid, eid, email_type) ' .
    '  SELECT :target_nid, eid, email_type ' .
    '    FROM {webform_confirm_email} ' .
    '      WHERE nid=:template_nid ' ,
    array(':target_nid' => $node->nid, ':template_nid' => $template->nid)
  );
}

/**
 * Implements hook_webform_template_update().
 */
function webform_confirm_email_webform_template_update($node, $template) {
  db_delete('webform_confirm_email')->condition('nid', $node->nid)->execute();
  webform_confirm_email_webform_template_insert($node, $template);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function webform_confirm_email_form_webform_results_download_form_alter(&$form, &$form_state, $form_id) {
  $options = array(
    WEBFORM_CONFIRM_EMAIL_FILTER_NONE        => t('Download all submissions'),
    WEBFORM_CONFIRM_EMAIL_FILTER_CONFIRMED   => t('Download only confirmed submissions'),
    WEBFORM_CONFIRM_EMAIL_FILTER_UNCONFIRMED => t('Download only unconfirmed submissions'),
  );
  $form['range']['confirmed']= array(
    '#type'          => 'radios',
    '#title'         => t('You can restrict the download to include only (un)confirmed submissions'),
    '#default_value' => WEBFORM_CONFIRM_EMAIL_FILTER_NONE,
    '#options'       => $options,
    '#access'        => TRUE,
  );

  $form['#submit'] = array('webform_confirm_email_results_download_form_submit');

  return $form;
}

/**
 * Copied and adapted from webform/includes/webform.report.inc:
 * function webform_results_download_form_submit
 */
function webform_confirm_email_results_download_form_submit(&$form, &$form_state) {
  $node = $form_state['values']['node'];
  $format = $form_state['values']['format'];

  $options = array(
    'delimiter' => $form_state['values']['delimiter'],
    'components' => array_keys(array_filter($form_state['values']['components'])),
    'header_keys' => $form_state['values']['header_keys'],
    'select_keys' => $form_state['values']['select_keys'],
    'select_format' => $form_state['values']['select_format'],
    'range' => $form_state['values']['range'],
    'download' => $form_state['values']['download'],
  );

  $filters = array();
  switch ($form_state['values']['range']['confirmed']) {
    case WEBFORM_CONFIRM_EMAIL_FILTER_CONFIRMED:
      $filters['confirmed'] = 1;
      break;
    case  WEBFORM_CONFIRM_EMAIL_FILTER_UNCONFIRMED:
      $filters['confirmed'] = 0;
      break;
  }
  $defaults = webform_results_download_default_options($node, $format);
  $options += $defaults;
  $options['range'] += $defaults['range'];

  // Use a pre-built list of SIDs provided by validate handlers (if any).
  if (isset($form_state['values']['sids'])) {
    $options['sids'] = $form_state['values']['sids'];
  }
  // Retrieve the list of required SIDs.
  elseif ($options['range']['range_type'] != 'all' || !empty($filters)) {
    $options['sids'] = webform_confirm_email_download_sids($form_state['values']['node']->nid, $form_state['values']['range'], NULL, $filters);
  }

  // Determine an appropriate batch size based on the form and server specs.
  if (!isset($options['range']['batch_size'])) {
    // Start the batch size at 50,000 per batch, but divide by number of
    // components in the form. e.g. If a form had 10 components, it would
    // export 5,000 submissions at a time.
    $batch_size = ceil(50000 / max(1, count($form_state['values']['node']->webform['components'])));

    // Every 32MB of additional memory after 64MB adds a multiplier in size.
    $memory_limit = parse_size(ini_get('memory_limit'));
    $mb = 1048576;
    $memory_modifier = max(1, ($memory_limit - (64 * $mb)) / (32 * $mb));
    $batch_size = ceil($batch_size * $memory_modifier);

    // For time reasons, limit the batch size to 10,000.
    $batch_size = min($batch_size, 10000);

    // Allow a non-UI configuration to override the batch size.
    $batch_size = variable_get('webform_export_batch_size', $batch_size);

    $options['range']['batch_size'] = $batch_size;
  }

  $options['file_name'] = _webform_export_tempname();

  // Set up a batch to export the results.
  $batch = webform_results_export_batch($node, $format, $options);
  batch_set($batch);
}

/**
 * Copied and adapted from webform/includes/webform.report.inc:
 * function webform_download_sids
 */
function webform_confirm_email_download_sids($nid, $range_options, $uid = NULL, $filters = NULL) {
  $query = db_select('webform_submissions', 'ws')
    ->fields('ws', array('sid'))
    ->condition('nid', $nid)
    ->addTag('webform_download_sids');

  if (isset($filters) == TRUE) {
    foreach($filters as $column => $value) {
      $query->condition($column, $value);
    }
  }

  switch ($range_options['range_type']) {
    case 'all':
      // All Submissions.
      $query->orderBy('sid', 'ASC');
      break;
    case 'new':
      // All Since Last Download.
      $download_info = webform_download_last_download_info($nid, $uid);
      $last_sid = $download_info ? $download_info['sid'] : 0;
      $query
        ->condition('sid', $last_sid, '>')
        ->orderBy('sid', 'ASC');
      break;
    case 'latest':
      // Last x Submissions.
      $start_sid = webform_download_latest_start_sid($nid, $range_options['latest'], $range_options['completion_type']);
      $query->condition('sid', $start_sid, '>=');
      break;
    case 'range':
      // Submissions Start-End.
      $query->condition('sid', $range_options['start'], '>=');
      if ($range_options['end']){
        $query->condition('sid', $range_options['end'], '<=');
      }
      $query->orderBy('sid', 'ASC');
      break;
    case 'range_serial':
      // Submissions Start-End, using serial numbers.
      $query->condition('serial', $range_options['start'], '>=');
      if ($range_options['end']){
        $query->condition('serial', $range_options['end'], '<=');
      }
      $query->orderBy('serial', 'ASC');
      break;
  }

  // Filter down to draft or finished submissions.
  if (!empty($range_options['completion_type']) && $range_options['completion_type'] !== 'all') {
    $query->condition('is_draft', (int) ($range_options['completion_type'] === 'draft'));
  }
    // Set batch properties. Unfortunately the pager query class reads directly
  // from $_GET['page'] to determine the current page number, so we have to set
  // this super-global and then restore it after executing the query.
  if (isset($range_options['batch_number']) && isset($range_options['batch_size'])) {
    if (isset($_GET['page'])) {
      $current_page = $_GET['page'];
    }
    $_GET['page'] = $range_options['batch_number'];
    $query = $query->extend('PagerDefault');
    $query->limit($range_options['batch_size']);
    $query->element(0);
  }

  $sids = $query->execute()->fetchCol();

  // Restore the current page number (if any).
  if (isset($current_page)) {
    $_GET['page'] = $current_page;
  }

  return $sids;
}

/**
 * Implements hook_views_api().
 */
function webform_confirm_email_views_api() {
  return array(
    'api'  => 3.0,
    'path' => drupal_get_path('module', 'webform_confirm_email') . '/views',
  );
}
