<?php

/**
 * @file pw_donation_form.module
 * helper functions for donation form.
 */

/**
 * Implements hook_form_alter()..
 */
function pw_donation_form_form_alter(&$form, &$form_state, $form_id) {
  if (drupal_get_path_alias() == 'donation-form') { # $form_id == 'webform_client_form_10384'
	pw_donation_form_set_empty_value($form['submitted']['fieldset_donationform_yourdonation']['donation_target']);
	pw_donation_form_set_empty_value($form['submitted']['fieldset_donationform_yourdata']['personal_prefix']);
	$form['submitted']['fieldset_donationform_paymentinfo']['donation_date_start']['#process'][] = 'pw_donation_form_process_date';

   // custom validations
    $form['#validate'][] = 'pw_donation_form_form_validate';
  }
}

// set empty value
function pw_donation_form_set_empty_value(&$element){
  $element['#empty_option'] = '- '.$element['#title'].' -';
}

// set date
function pw_donation_form_process_date(&$element){

    // change day type to hidden
    $element['day']['#type'] = 'hidden';

    // set value for day
    if(!empty($element['#value']['month']) && !empty($element['#value']['year'])){
      if($element['#value']['year'].'-'.$element['#value']['month'] > date('Y-n')){
        $element['day']['#value'] = '1';
      }
      else{
        $element['day']['#value'] = date('d');
      }
    }
    else{
      $element['day']['#value'] = '';
    }
    return $element;
}

// custom validations
function pw_donation_form_form_validate($form_id, $form_values){
  // check if amount higher than 5 euros
  if($form_values['values']['submitted']['fieldset_donationform_yourdonation']['donation_amount'] == 'free' && $form_values['values']['submitted']['fieldset_donationform_yourdonation']['donation_free_amount'] < 5){
    form_set_error("donation_amount_free", 'Bitte tragen Sie einen Wert über 5 Euro ein.');
  }

  // check if either iban is filled or Kontonummer & Bankleitzahl
  $check_iban = !empty($form_values['values']['submitted']['fieldset_donationform_paymentinfo']['payment_accordion']['payment_tab_sepa']['payment_sepa_iban']);

  $check_dd_account = !empty($form_values['values']['submitted']['fieldset_donationform_paymentinfo']['payment_accordion']['payment_tab_direct_debit']['payment_direct_debit_account']);

  $check_dd_bank = !empty($form_values['values']['submitted']['fieldset_donationform_paymentinfo']['payment_accordion']['payment_tab_direct_debit']['payment_direct_debit_bank']);

  if(!$check_dd_account && $check_dd_bank){
    form_set_error("payment_direct_debit_account", 'Bitte füllen Sie das Feld für die Kontonummer aus.');
  }
  if($check_dd_account && !$check_dd_bank){
    form_set_error("payment_direct_debit_bank", 'Bitte füllen Sie das Feld für die Bankleitzahl aus.');
  }
  if(!$check_iban && !$check_dd_account && !$check_dd_bank){
    form_set_error("payment_sepa_iban", 'Bitte füllen Sie das Feld für die IBAN aus oder alternativ die Felder für Kontonummer und Bankleitzahl.');
  }
}
