<?php
/**
 * @file
 * Code for the PW Search api feature.
 */

include_once 'pw_search_api.features.inc';
include_once 'pw_customfacets.inc';

function pw_search_api_search_api_views_query_alter(view &$view, SearchApiViewsQuery &$query) { // check for display
  if ($view->name == 'vote_search' && arg(0) == 'node' && is_numeric(arg(1))) {
    // Adds filter to only show items for the current node.
    $query->where[1]['conditions'][] = array("field_vote_node", arg(1), "=");
  }
}
