<?php
/**
 * @file
 */

include_once('pw_api.features.inc');

/**
 * Helper function used by hooks below for translating XML root elements.
 *
 * Translates the root elements of the following API parts:
 * areacodes.xml:               taxonomy_term_datas -> areacodes, taxonomy_term_data -> areacode
 * constituencies.xml:          taxonomy_term_datas -> constituencies, taxonomy_term_data -> constituency
 * dialogues.xml:               nodes -> dialogues, node -> dialogue
 * parliaments.xml:             taxonomy_term_datas -> parliaments, taxonomy_term_data -> parliament
 * profile.xml || profiles.xml: user_revisions -> profiles, user_revision -> profile
 *
 * This is hard-coded in here, because it is announced, that the root element
 * is changeable in the next version of the views export module. After the update,
 * this code will become obsolete.
 *
 * @param String $input
 * @return String
 */
function tag_replace($input)
{
    // Get the current request path:
    $tmparr = explode("/", request_path());
    $count = count($tmparr);
    $requestname = "";
    if ($count != 0) {
        $requestname = str_replace(".xml", "", $tmparr[$count - 1]);
    }

    $replace_arr = array(); // IMPORTANT: The order within this array is crucial. Longer names have to be inserted _before_ shorter ones.
    switch ($requestname) {
        case "areacodes":
            $replace_arr = array("taxonomy_term_datas" => "areacodes", "taxonomy_term_data" => "areacode");
            break;
        case "constituencies":
            $replace_arr = array("taxonomy_term_datas" => "constituencies", "taxonomy_term_data" => "constituency");
            break;
        case "dialogues":
            $replace_arr = array("nodes" => "dialogues", "node" => "dialogue");
            break;
        case "parliaments":
            $replace_arr = array("taxonomy_term_datas" => "parliaments", "taxonomy_term_data" => "parliament");
            break;
        case "profile":
        case "profile-authorized":
        case "profiles":
            $replace_arr = array("user_revisions" => "profiles", "user_revision" => "profile");
            break;
        default:
            // do nothing
            break;
    }

//  $replace_arr = variable_get('pw_api_replacement', array());
    if (array_key_exists($input, $replace_arr)) {
        return $replace_arr[$input];
    }
    return $input;
}

function pw_api_preprocess_views_data_export_xml_header(&$vars)
{
    $vars['root_node'] = tag_replace($vars['root_node']);
}

function pw_api_preprocess_views_data_export_xml_footer(&$vars)
{
    $vars['root_node'] = tag_replace($vars['root_node']);
}

/**
 * Preprocess xml output template.
 */
function pw_api_preprocess_views_data_export_xml_body(&$vars)
{
    _views_data_export_header_shared_preprocess($vars);
    _views_data_export_body_shared_preprocess($vars);

    // Compute the tag name based on the views base table, minus any trailing 's'.
    $vars['item_node'] = _views_data_export_xml_tag_clean(rtrim($vars['view']->base_table, 's'));
    $vars['item_node'] = tag_replace($vars['item_node']);

    foreach ($vars['themed_rows'] as $num => $row) {
        foreach ($row as $field => $content) {
            // Prevent double encoding of the ampersand. Look for the entities produced by check_plain().
            $content = preg_replace('/&(?!(amp|quot|#039|lt|gt);)/', '&amp;', $content);


            // insert CDATA into dialogue fields:
            if ($field == "body" || $field == "comment_body" || $field == "field_dialogue_annotation_1") {
                $content = '<![CDATA[' . str_replace(']]>', ']]]]><![CDATA[>', $content) . ']]>';
            }

            $vars['themed_rows'][$num][$field] = array(); // reset the array, otherwise strange things will happen
            if (substr_count($content, "||") > 0) { // Multiple-Feld
                $tmp_arr = explode("||", $content);
                if (substr_count($tmp_arr[0], "##") > 0) { // Multiple-Feld mit Attributen
                    $collection_arr = array();
                    foreach ($tmp_arr as $tmp) {
                        $inner_tmp_arr = explode("##", $tmp);
                        $collection_arr[] = array(
                            "attribute_name" => $inner_tmp_arr[0],
                            "attribute_value" => $inner_tmp_arr[1],
                            "value" => $inner_tmp_arr[2]);
                    }
                    $vars['themed_rows'][$num][$field]["type"] = "multiplefield_with_attributes";
                    $vars['themed_rows'][$num][$field]["content"] = $collection_arr;
                } else { // Multiple-Feld ohne Attribute
                    $vars['themed_rows'][$num][$field]["type"] = "multiplefield_without_attributes";
                    $vars['themed_rows'][$num][$field]["content"] = $tmp_arr;
                }
            } else if (substr_count($content, "##") > 0) { // Single field with attributes
                $inner_tmp_arr = explode("##", $content);
                $vars['themed_rows'][$num][$field]["type"] = "singlefield_with_attributes";
                $vars['themed_rows'][$num][$field]["content"] = array(
                    "attribute_name" => $inner_tmp_arr[0],
                    "attribute_value" => $inner_tmp_arr[1],
                    "value" => $inner_tmp_arr[2]);
            } else if (substr_count($content, "}{") > 0) { // Single field with single subfields
                $tmp_arr = explode("}{", $content);
                $collection_arr = array();
                foreach ($tmp_arr as $tmp) {
                    $inner_tmp_arr = explode("**", $tmp);
                    $collection_arr[] = array(
                        "name" => $inner_tmp_arr[0],
                        "value" => $inner_tmp_arr[1]);
                }
                $vars['themed_rows'][$num][$field]["type"] = "singlefield_with_single_subfields";
                $vars['themed_rows'][$num][$field]["content"] = $collection_arr;
            } else {
                $vars['themed_rows'][$num][$field]["type"] = "singlefield_without_attributes";
                $vars['themed_rows'][$num][$field]["content"] = $content;
            }
            // Case 1: Multiple Field with additional attributes
            // example: a##b##c||d##e##f =>
            // <examples>
            //   <example a="b">c</bsp>
            //   <example d="e">f</bsp>
            // </examples>
            //
            // Case 2: Multiple field without additional attributes
            // example: a||b =>
            // <examples>
            //   <example>a</bsp>
            //   <example>b</bsp>
            // </examples>
            //
            // Case 3: Single field with single subfields
            // example: name1**val1}{name2**val2 =>
            // <example>
            //   <name1>val1</name1>
            //   <name2>val2</name1>
            // </example>
        }
    }

    foreach ($vars['header'] as $field => $header) {
        // If there is no field label, use 'no name'.
        $vars['xml_tag'][$field] = !empty($header) ? $header : 'no name';
        if ($vars['options']['transform']) {
            switch ($vars['options']['transform_type']) {
                case 'dash':
                    $vars['xml_tag'][$field] = str_replace(' ', '-', $header);
                    break;
                case 'underline':
                    $vars['xml_tag'][$field] = str_replace(' ', '_', $header);
                    break;
                case 'camel':
                    $vars['xml_tag'][$field] = str_replace(' ', '', ucwords(strtolower($header)));
                    // Convert the very first character of the string to lowercase.
                    $vars['xml_tag'][$field][0] = strtolower($vars['xml_tag'][$field][0]);
                    break;
                case 'pascal':
                    $vars['xml_tag'][$field] = str_replace(' ', '', ucwords(strtolower($header)));
                    break;
            }
        }
        // We should always try to output valid XML.
        $vars['xml_tag'][$field] = _views_data_export_xml_tag_clean($vars['xml_tag'][$field]);
        $vars['xml_tag'][$field] = tag_replace($vars['xml_tag'][$field]);
    }
}

function pw_api_views_pre_view(&$view, &$display_id, &$args)
{
    if ($view->name == 'pw_api_internal_profile') {
        $allowed_ips = variable_get('pw_api_allowed_ips', array());
        $current_ip_is_allowed = false;
        $current_ip = $_SERVER['REMOTE_ADDR'];
        foreach ($allowed_ips as $allowed_ip) {
            if ($allowed_ip == $current_ip) {
                $current_ip_is_allowed = true;
                break;
            } else if (substr_count($allowed_ip, '.*') > 0) {
                $allowed_ip = str_replace('.*', '', $allowed_ip);
                if (strpos($current_ip, $allowed_ip) === 0) {
                    $current_ip_is_allowed = true;
                    break;
                }
            }
        }
        if (!$current_ip_is_allowed)
            $view->destroy();
    }
}

/**
 * Implements hook_menu().
 *
 * @return array
 */
function pw_api_menu()
{
    $items = array();
    $items['admin/config/pw/pw_api/settings'] = array(
        'title' => 'PW API settings',
        'description' => 'Allows to add allowed IP addresses for the internal API.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('pw_api_admin_settings'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'pw_api.admin.inc',
    );
    $items['api/%/%/profiles.xml'] = array(
        'page callback' => 'pw_api_profiles',
        'page arguments' => array(1, 2),
        'access callback' => TRUE,
        'delivery callback' => 'pw_api_deliver_xml',
        'type' => MENU_CALLBACK,
    );
    $items['api/%/%/deputies.xml'] = array(
        'page callback' => 'pw_api_profiles',
        'page arguments' => array(1, 2),
        'access callback' => TRUE,
        'delivery callback' => 'pw_api_deliver_xml',
        'type' => MENU_CALLBACK,
    );
    $items['api/%/%/candidates.xml'] = array(
        'page callback' => 'pw_api_profiles',
        'page arguments' => array(1, 2),
        'access callback' => TRUE,
        'delivery callback' => 'pw_api_deliver_xml',
        'type' => MENU_CALLBACK,
    );
    $items['api/%/%/%/%/profiles.xml'] = array(
        'page callback' => 'pw_api_profiles',
        'page arguments' => array(1, 2, 3, 4),
        'access callback' => TRUE,
        'delivery callback' => 'pw_api_deliver_xml',
        'type' => MENU_CALLBACK,
    );
    $items['api/%/%/%/%/deputies.xml'] = array(
        'page callback' => 'pw_api_profiles',
        'page arguments' => array(1, 2, 3, 4),
        'access callback' => TRUE,
        'delivery callback' => 'pw_api_deliver_xml',
        'type' => MENU_CALLBACK,
    );
    $items['api/%/%/%/%/candidates.xml'] = array(
        'page callback' => 'pw_api_profiles',
        'page arguments' => array(1, 2, 3, 4),
        'access callback' => TRUE,
        'delivery callback' => 'pw_api_deliver_xml',
        'type' => MENU_CALLBACK,
    );
    $items['api/%/%/profiles.json'] = array(
        'page callback' => 'pw_api_profiles',
        'page arguments' => array(1, 2),
        'access callback' => TRUE,
        'delivery callback' => 'pw_api_deliver_json',
        'type' => MENU_CALLBACK,
    );
    $items['api/%/%/%/%/profiles.json'] = array(
        'page callback' => 'pw_api_profiles',
        'page arguments' => array(1, 2, 3, 4),
        'access callback' => TRUE,
        'delivery callback' => 'pw_api_deliver_json',
        'type' => MENU_CALLBACK,
    );
    $items['api/%/%/profiles.csv'] = array(
        'page callback' => 'pw_api_profiles',
        'page arguments' => array(1, 2),
        'access callback' => TRUE,
        'delivery callback' => 'pw_api_deliver_csv',
        'type' => MENU_CALLBACK,
    );
    $items['api/%/%/%/%/profiles.csv'] = array(
        'page callback' => 'pw_api_profiles',
        'page arguments' => array(1, 2, 3, 4),
        'access callback' => TRUE,
        'delivery callback' => 'pw_api_deliver_csv',
        'type' => MENU_CALLBACK,
    );
    return $items;
}

/**
 * Delivery callback; returns XML.
 *
 * @param array $page_result
 */
function pw_api_deliver_xml($page_result)
{
    drupal_add_http_header('Content-type', 'text/xml; charset=utf8');

    if (is_int($page_result)) {
        switch ($page_result) {
            case MENU_NOT_FOUND:
                drupal_add_http_header('Status', '404 Not Found');
                break;
        }
    } else {
        $writer = new XmlWriter();
        $writer->openUri('php://output');
        $writer->setIndent(TRUE);
        $writer->setIndentString('    ');
        $writer->startDocument('1.0', 'UTF-8');
        $writer->startElement('profiles');
        foreach ($page_result as $item) {
            $writer->startElement('profile');
            $writer->writeAttribute('edited', $item['edited']);
            $writer->writeElement('name', $item['name']);
            $writer->writeElement('uuid', $item['uuid']);
            $writer->writeElement('gender', $item['gender']);
            $writer->writeElement('first_name', $item['first_name']);
            $writer->writeElement('last_name', $item['last_name']);
            $writer->writeElement('party', $item['party']);
            $writer->writeElement('parliament', $item['parliament']);
            $writer->startElement('constituency');
            $writer->writeElement('uuid', $item['constituency']['uuid']);
            $writer->writeElement('name', $item['constituency']['name']);
            $writer->writeElement('number', $item['constituency']['number']);
            $writer->endElement();
            $writer->writeElement('education', $item['education']);
            $writer->startElement('location');
            $writer->writeElement('country', $item['location']['country']);
            $writer->writeElement('county', $item['location']['county']);
            $writer->writeElement('city', $item['location']['city']);
            $writer->writeElement('postal_code', $item['location']['postal_code']);
            $writer->endElement();
            $writer->startElement('picture');
            $writer->writeElement('url', $item['picture']['url_picture']);
            $writer->writeElement('copyright', $item['picture']['copyright_picture']);
            $writer->endElement();
            $writer->writeElement('questions_get', $item['questions_get']);
            $writer->writeElement('answers_give', $item['answers_give']);
            $writer->writeElement('url_profile', $item['url_profile']);
            $writer->endElement();
        }
        $writer->endElement();
        $writer->flush();
    }
}

/**
 * Delivery callback; returns JSON.
 *
 * @param array $page_result
 */
function pw_api_deliver_json($page_result)
{
    drupal_add_http_header('Content-Type', 'application/json');

    if (is_int($page_result)) {
        switch ($page_result) {
            case MENU_NOT_FOUND:
                drupal_add_http_header('Status', '404 Not Found');
                break;
        }
    } else {
        print drupal_json_encode($page_result);
    }
}

/**
 * Delivery callback; returns CSV.
 *
 * @param array $page_result
 */
function pw_api_deliver_csv($page_result)
{
    drupal_add_http_header('Content-type', 'text/csv; charset=utf8');

    if (is_int($page_result)) {
        switch ($page_result) {
            case MENU_NOT_FOUND:
                drupal_add_http_header('Status', '404 Not Found');
                break;
        }
    } else {
        $handle = fopen('php://output', 'w');
        foreach ($page_result as $item) {
            $fields = array(
                $item['uuid'],
                $item['gender'],
                $item['name'],
                $item['first_name'],
                $item['last_name'],
                $item['party'],
                $item['constituency']['uuid'],
                $item['constituency']['name'],
                $item['constituency']['number'],
            );
            fputcsv($handle, $fields);
        }
    }
}

/**
 * Page callback; returns selection of profiles based on given filters.
 *
 * Sets a custom cache ttl.
 *
 * @param string $parliament_filter
 *
 * @param string $parliament_argument
 *
 * @param string $filter
 *
 * @param string $argument
 *
 * @return array
 *   The profiles as an associative array
 */
function pw_api_profiles($parliament_filter, $parliament_argument, $filter = NULL, $argument = NULL)
{
    $query = db_select('user_revision', 'ur');
    $users_alias = $query->join('users', 'u', '%alias.uid = ur.uid');
    $roles_alias = $query->join('users_roles', 'uro', '%alias.uid = ur.uid');
    $users_cache_alias = $query->join('user_archive_cache', 'uac', '%alias.vid = ur.vid');
    $user_gender_alias = $query->leftJoin('field_revision_field_user_gender', 'frfug', "%alias.revision_id = ur.vid AND %alias.entity_type = 'user' AND %alias.language='und'"); // choose only one language, otherwise this user will be displayed more than once
    $user_fname_alias = $query->leftJoin('field_revision_field_user_fname', 'frfuf', "%alias.revision_id = ur.vid AND %alias.entity_type = 'user' AND %alias.language='und'"); // dito
    $user_lname_alias = $query->leftJoin('field_revision_field_user_lname', 'frful', "%alias.revision_id = ur.vid AND %alias.entity_type = 'user' AND %alias.language='und'"); // dito
    $user_party_alias = $query->leftJoin('field_revision_field_user_party', 'frfup', "%alias.revision_id = ur.vid AND %alias.entity_type = 'user' AND %alias.delta=0"); // we assume that a user is only in one party
    $user_constituency_alias = $query->leftJoin('field_revision_field_user_constituency', 'frfuc', "%alias.revision_id = ur.vid AND %alias.entity_type = 'user'"); // we assume that a user is in only one constituency
    // removed  AND %alias.delta=0 from field_revision_field_user_constituency query part
    $user_parliament_alias = $query->leftJoin('field_revision_field_user_parliament', 'frfupm', "%alias.revision_id = ur.vid AND %alias.entity_type = 'user' AND %alias.delta=0"); // we assume that a user is in only one parliament
    $term_party_alias = $query->join('taxonomy_term_data', 'p', "%alias.tid = $user_party_alias.field_user_party_tid");
    $term_constituency_alias = $query->leftJoin('taxonomy_term_data', 'c', "%alias.tid = $user_constituency_alias.field_user_constituency_tid");
    $term_parliament_alias = $query->join('taxonomy_term_data', 'pm', "%alias.tid = $user_parliament_alias.field_user_parliament_tid");
    $constituency_number_alias = $query->leftJoin('field_data_field_constituency_nr', 'fdfcn', "%alias.entity_id = $user_constituency_alias.field_user_constituency_tid AND %alias.entity_type = 'taxonomy_term'");
    $user_education_alias = $query->leftJoin('field_revision_field_user_education', 'frfue', "%alias.revision_id = ur.vid AND %alias.entity_type = 'user' AND %alias.language='und'");
    $user_address_alias = $query->leftJoin('field_revision_field_user_address', 'frfua', "%alias.revision_id = ur.vid AND %alias.entity_type = 'user' AND %alias.language='und'");
    $user_picture_alias = $query->leftJoin('field_revision_field_user_picture', 'frfupic', "%alias.revision_id = ur.vid AND %alias.entity_type = 'user' AND %alias.language='und'");
    $user_file_alias = $query->leftJoin('file_managed', 'frfufile', "%alias.fid = frfupic.field_user_picture_fid");
    $user_copyright_alias = $query->leftJoin('field_revision_field_image_copyright', 'frfucr', "%alias.revision_id = ur.vid AND %alias.entity_type = 'file' AND %alias.language='und'");
    $user_questions_get_alias = $query->leftJoin('field_data_field_user_questions_get', 'frfuqg', "%alias.revision_id = ur.vid AND %alias.entity_type = 'user' AND %alias.language='und'");
    $user_answers_give_alias = $query->leftJoin('field_data_field_user_answers_give', 'frfuag', "%alias.revision_id = ur.vid AND %alias.entity_type = 'user' AND %alias.language='und'");

    $query->addField('ur', 'name');
    $query->addField('ur', 'vid');
    $query->addField('ur', 'timestamp');
    $query->addField($users_alias, 'uuid');
    $query->addField($user_gender_alias, 'field_user_gender_value', 'gender');
    $query->addField($user_fname_alias, 'field_user_fname_value', 'first_name');
    $query->addField($user_lname_alias, 'field_user_lname_value', 'last_name');
    $query->addField($term_party_alias, 'name', 'party');
    $query->addField($term_parliament_alias, 'name', 'parliament');
    $query->addField($term_constituency_alias, 'name', 'constituency_name');
    $query->addField($term_constituency_alias, 'uuid', 'constituency_uuid');
    $query->addField($constituency_number_alias, 'field_constituency_nr_value', 'constituency_number');
    $query->addField($user_education_alias, 'field_user_education_value', 'education');
    $query->addField($user_address_alias, 'field_user_address_country', 'location_country');
    $query->addField($user_address_alias, 'field_user_address_administrative_area', 'location_county');
    $query->addField($user_address_alias, 'field_user_address_locality', 'location_city');
    $query->addField($user_address_alias, 'field_user_address_postal_code', 'location_postal_code');
    $query->addField($user_file_alias, 'uri', 'picture_uri');
    $query->addField($user_copyright_alias, 'field_image_copyright_value', 'copyright');
    $query->addField($user_questions_get_alias, 'field_user_questions_get_value', 'questions_get');
    $query->addField($user_answers_give_alias, 'field_user_answers_give_value', 'answers_give');

    $feedname = current(explode(".", basename($_SERVER['REQUEST_URI'])));

    switch ($feedname) {
        case 'candidates':
            $rid = 185431326;
            break;
        case 'deputies':
            $rid = 140336230;
            break;
        case 'politicians':
            $rid = 181527986;
            break;
        case 'profiles':
            $rid = 181527986;
            break;
    }

    $query->where("$roles_alias.rid = :rid", array(':rid' => $rid))
        ->orderBy("$users_alias.uuid", 'ASC')
        ->orderBy('ur.vid', 'DESC');

    if ($parliament_filter == 'parliament') {
        $query->where("$term_parliament_alias.name = :p_name", array(':p_name' => $parliament_argument));
    } elseif ($parliament_filter == 'parliament-by-uuid') {
        $query->where("$term_parliament_alias.uuid = :p_uuid", array(':p_uuid' => $parliament_argument));
    } else {
        return MENU_NOT_FOUND;
    }

    switch ($filter) {
        case 'constituency':
            $query->where("$term_constituency_alias.name = :c_name", array(':c_name' => $argument));
            break;
        case 'constituency-by-uuid':
            $query->where("$term_constituency_alias.uuid = :c_uuid", array(':c_uuid' => $argument));
            break;
        case 'areacode':
        case 'areacode-by-uuid':
            $user_constituency_areacodes_alias = $query->join('field_revision_field_constituency_area_codes', 'frfcac', "%alias.revision_id = $user_constituency_alias.field_user_constituency_tid");
            $term_areacodes_alias = $query->join('taxonomy_term_data', 'pl', "%alias.tid = $user_constituency_areacodes_alias.field_constituency_area_codes_tid");
            if ($filter == "areacode-by-uuid") {
                $query->where("$term_areacodes_alias.uuid = :a_uuid", array(':a_uuid' => $argument));
            } else {
                $query->where("$term_areacodes_alias.name = :a_name", array(':a_name' => $argument));
            }
            break;
    }

    $profiles = array();

    foreach ($query->execute() as $row) {
        // set picture url
        $url_picture = !empty($row->picture_uri) ? file_create_url($row->picture_uri) : '';

        // set full county
        switch ($row->location_county) {
            case 'BW':
                $county = 'Baden-Wuerttemberg';
                break;
            case 'BY':
                $county = 'Bavaria';
                break;
            case 'BE':
                $county = 'Berlin';
                break;
            case 'BB':
                $county = 'Brandenburg';
                break;
            case 'HB':
                $county = 'Bremen';
                break;
            case 'HH':
                $county = 'Hamburg';
                break;
            case 'HE':
                $county = 'Hesse';
                break;
            case 'MV':
                $county = 'Mecklenburg-Vorpommern';
                break;
            case 'NI':
                $county = 'Lower Saxony';
                break;
            case 'NW':
                $county = 'North Rhine-Westphalia';
                break;
            case 'RP':
                $county = 'Rhineland-Palatinate';
                break;
            case 'SL':
                $county = 'Saarland';
                break;
            case 'SN':
                $county = 'Saxony';
                break;
            case 'ST':
                $county = 'Saxony-Anhalt';
                break;
            case 'SH':
                $county = 'Schleswig-Holstein';
                break;
            case 'TH':
                $county = 'Thuringia';
                break;
            default:
                $county = '';
        }

        // set url to profile # .'/archive/'.$row->vid
        $url_profile = url('profile/' . $row->name, array('absolute' => TRUE));

        $profiles[] = array(
            'edited' => date('Y-m-d H:i', $row->timestamp),
            'name' => $row->name,
            'gender' => $row->gender,
            'first_name' => $row->first_name,
            'last_name' => $row->last_name,
            'uuid' => $row->uuid,
            'party' => $row->party,
            'parliament' => $row->parliament,
            'constituency' => array(
                'uuid' => $row->constituency_uuid,
                'name' => $row->constituency_name,
                'number' => $row->constituency_number,
            ),
            'education' => $row->education,
            'location' => array(
                'country' => $row->location_country,
                'county' => t($county),
                'city' => $row->location_city,
                'postal_code' => $row->location_postal_code,
            ),
            'picture' => array(
                'url_picture' => $url_picture,
                'copyright_picture' => $row->copyright,
            ),
            'questions_get' => $row->questions_get,
            'answers_give' => $row->answers_give,
            'url_profile' => $url_profile,
        );
    }

    drupal_add_http_header('Cache-Control', 'public, max-age=86400');

    return $profiles;
}


function pw_api_views_query_alter(&$view, &$query)
{
    if ($view->name == 'pw_api_internal_profile') {

        // add join user_archive_cache table to get rid of duplicates
        $join = new views_join();
        $join->table = 'user_archive_cache';
        $join->field = 'vid';
        $join->left_table = 'user_revision';
        $join->left_field = 'vid';
        $join->type = 'INNER';
        $query->add_relationship('user_archive_cache', $join, 'user_revision');
    }
}
