<?php

/**
 * This module overrides the default interface for twitter presented to a logged
 * in politician by a more convenient one.
 * 
 */

/**
 * Removes "Twitter accounts" sub menu from user
 * @param type $items 
 */
function pw_twitter_menu_alter(&$items) {
  unset($items["user/%user/edit/twitter"]);
}

/**
 * Saves a newly added twitter account. It checks, if it is already existing
 * for another user and does _not_ override it in case.
 * @param type $new_value
 * @param type $account
 * @return type 
 */
function pw_twitter_save($new_value, $account) {
  // load twitter module functions (#AW-1553)
  module_load_include('inc', 'twitter', 'twitter');

  // prevent Twitter accounts added by other users from being overriden by this user:
  if (twitter_account_load($new_value)) {
    form_set_error('screen_name', t('The Twitter account <em>@screen_name</em> has been added already.',
      array('@screen_name' => $new_value)));
    return false;
  }
  
  $twitter = twitter_connect();
  if (!$twitter) {
    // Gdata import fails on empty $twitter objects, #AW-1553.
    // @TODO beautify: maybe set a warning message?
    return false;
  }
  else {
    $twitter_account = $twitter->users_show($new_value, FALSE);
    if (!isset($twitter_account->id)) {
      form_set_error('screen_name', t('Could not add the Twitter account <em>@name</em>. ' .
        'Check the recent messages log.', array('@name' => $new_value)));
    } else {
      $twitter_account->uid = $account->uid;
      $twitter_account->import = true;
      twitter_account_save($twitter_account, FALSE);
      drupal_set_message(t('Twitter account added successfully'));
    }
    return true;
  }
}

/**
 * Deletes all twitter accounts (can only be one) added to a user with account $account
 * @param type $account 
 */
function pw_twitter_delete($account) {
  // load twitter module functions (#AW-1553)
  module_load_include('inc', 'twitter', 'twitter');

  $accounts = twitter_twitter_accounts($account);
  foreach ($accounts as $account) {
    $twitter_account = twitter_account_load($account->id);
    twitter_account_delete($account->id);
    drupal_set_message(t('The Twitter account <em>!account</em> was deleted.',
      array('!account' => $twitter_account->screen_name)));
  }
  drupal_set_message(t('The Twitter account settings were updated.'));
}

/**
 * If a user is saved, this function checks whether a twitter account was added
 * or deleted. If it has changed, it is entered into the fields provided by the 
 * twitter module
 */
function pw_twitter_user_presave(&$edit, $account, $category) {
  if (array_key_exists('field_user_twitter_account', $edit)) {
    $new_value = $edit["field_user_twitter_account"]["und"]["0"]["value"];
    $original = $account->original->field_user_twitter_account;
    $old_value = $original["und"]["0"]["value"];
    $saved = false;
    if ($old_value == "" && $new_value != "") { // a new twitter account is initially set. Save it:
      $saved = pw_twitter_save($new_value, $account);
    } else if ($old_value != "" && $new_value != "" && $old_value != $new_value) {
      pw_twitter_delete($account);
      $saved = pw_twitter_save($new_value, $account);
    } else if ($old_value != "" && $new_value == "") {
      pw_twitter_delete($account);
    }
    if (!$saved) { // reset field if account is not saved properly
      $edit["field_user_twitter_account"]["und"]["0"]["value"] = "";
    }
  }
}
