<?php

/**
 * @file pw_forms_filter_alter.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_form_alter()..
 */
function pw_forms_filter_alter_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && $form_state['view']->name == 'profile_list_rev' && $form_state['view']->current_display == 'grid') {
	
	// prepate query
	$current_uri = check_plain(request_uri());
	$current_uri = rawurldecode($current_uri);
	$a_url = explode("/", $current_uri);
	$role_name = $a_url[1] == 'candidates'?'Candidate':'Deputy';
	$parliament_name = $a_url[2];
	$a_parameter = array(':role_name' => $role_name, ':parliament_name' => $parliament_name);

	// query database
	$sql = "SELECT tparty.tid, tparty.name
		FROM users AS u 
		INNER JOIN user_revision AS urev ON u.uid = urev.uid
		INNER JOIN users_roles AS ur ON u.uid = ur.uid 
		INNER JOIN role AS r ON ur.rid = r.rid 
		INNER JOIN field_revision_field_user_parliament AS uparl ON uparl.entity_type = 'user' AND u.uid = uparl.entity_id AND urev.vid = uparl.revision_id
		INNER JOIN taxonomy_term_data AS tparl ON uparl.field_user_parliament_tid = tparl.tid 
		INNER JOIN field_revision_field_user_party AS uparty ON uparty.entity_type = 'user' AND u.uid = uparty.entity_id AND urev.vid = uparty.revision_id 
		INNER JOIN taxonomy_term_data AS tparty ON uparty.field_user_party_tid = tparty.tid 
		WHERE r.name = :role_name AND tparl.name = :parliament_name";
    $result = db_query($sql, $a_parameter);
    $terms = $result->fetchAll();

    $options = array('All' => '- Any -');
	foreach ($terms as $term) {
      $options[$term->tid] = $term->name;
    }
	$form['field_user_party_tid']['#options'] = $options;
  }
}
