<?php

/*
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function migrate_committee_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'CommitteeTerm' => array(
        'class_name' => 'CommitteeTermMigration',
        'group_name' => 'committee',
      ),
    ),
  );
  return $api;
}
