<?php

/**
 * @file
 * Adds features to the default image gallery field:
 * - Enables a higher limit of fixed size galleries
 * - Disables unnecessary links in the edit popup
 */



function pw_image_gallery_form_field_ui_field_edit_form_alter(&$form, &$form_state, $form_id) {
  $form['field']['cardinality']["#options"] = array(FIELD_CARDINALITY_UNLIMITED => t('Unlimited')) + drupal_map_assoc(range(1, 60));
}

