<?php
/**
 * @file
 * Code for the PW Globals feature.
 */

include_once 'pw_globals.features.inc';

/**
 * Implements hook_query_alter().
 */
// function pw_globals_query_alter($query) {
//   if ($query->hasTag('node_export_features')) {
//     $query->condition('type', array('announcement', 'page', 'trustee', 'webform', 'pw_slider'), 'IN');
//   }
// }

/**
 * Custom: Checks if User (Revision) is Premium User
 */
function _pw_is_premium_user($user) {
  $term_premium_user = taxonomy_get_term_by_name('Premium User', 'pw_profile_roles_for_view_mode_switch');
  $tid_premium_user = key($term_premium_user);
  foreach ($user->field_user_roles_for_view_mode_s[LANGUAGE_NONE] as $role) {
    if ($tid_premium_user == $role['tid']) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Custom: Checks if profile is open for questions.
 */
function _pw_is_profile_consultable($user=FALSE) {
  if(!$user){
    $user = _pw_get_current_user();
    if(!$user){
      return FALSE;
    }
  }
  $profile_consultable = &drupal_static(__FUNCTION__.(isset($user->vid)?$user->vid:''));
  if (!isset($profile_consultable)) {
    $profile_consultable = FALSE;
    if(!isset($user->field_user_question_form_closed) || empty($user->field_user_question_form_closed)){
      if(_pw_is_parliament_active()){
        if(_pw_user_has_role($user, 'Candidate')){
          $parliament = _pw_get_current_parliament_term();
          if(!$parliament){
            return $profile_consultable;
          }
          $date_election = $parliament->field_parliament_election[LANGUAGE_NONE][0]['value'];
          if(empty($date_election)){
            return $profile_consultable;
          }
          $day_before_election = strtotime($date_election) - 6*60*60;
          if(time() > $day_before_election){
            return $profile_consultable;
          }
        }
        $profile_consultable = TRUE;
      }
    }
  }
  return $profile_consultable;
}

/**
 * Custom: Checks if User (Revision) has specific role.
 */
function _pw_user_has_role($user, $role) {
  $term_role = taxonomy_get_term_by_name($role, 'pw_profile_roles_for_view_mode_switch');
  $tid_role = key($term_role);
  foreach ($user->field_user_roles_for_view_mode_s[LANGUAGE_NONE] as $user_role) {
    if ($tid_role == $user_role['tid']) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Custom: Retrieve parliament term depending on currently viewed node or user.
 */
function _pw_get_current_parliament_term() {

  $term_parliament = &drupal_static(__FUNCTION__);
  if (!isset($term_parliament)) {

    // check if current page is a views page
    $menu_item = menu_get_item();
    if($menu_item['page_callback'] == 'views_page'){
      $terms = taxonomy_get_term_by_name(arg(1), 'parliaments');
      if(!empty($terms)){
        $term_parliament = array_shift($terms);
        return $term_parliament;
      }
    }

    switch (arg(0)) {

      // load by archived user profile
      case 'profile':
        $user = user_load_by_name(arg(1));
        $user_id = $user->uid;
        $vid = arg(3);
        $user = user_revision_load($user_id, $vid);
        $term_parliament_id = $user->field_user_parliament[LANGUAGE_NONE][0]['tid'];
        $term_parliament = taxonomy_term_load($term_parliament_id);
        break;

      // load by user profile
      case 'user':
        $user = menu_get_object('user');

        if (isset($user->field_user_parliament)) {
          $term_parliament_id = $user->field_user_parliament[LANGUAGE_NONE][0]['tid'];
          $term_parliament = taxonomy_term_load($term_parliament_id);
        }
        break;

      // load by node
      case 'node':
        $node = menu_get_object();
        if (isset($node->field_parliament)) {
          $term_parliament_id = $node->field_parliament[LANGUAGE_NONE][0]['tid'];
          $term_parliament = taxonomy_term_load($term_parliament_id);
        }
        break;
    }
  }
  return $term_parliament;
}

/**
 * Custom: check if parliament is active or not.
 */
function _pw_is_parliament_active($parliament=FALSE) {

  // if parliament was not set, try to retrieve it from current context
  if (!$parliament) {
    $parliament = _pw_get_current_parliament_term();
  }
  // if parliament was given as string, try to load full term
  elseif (is_string($parliament)) {
    $parliament = taxonomy_get_term_by_name($parliament, 'parliaments');
  }

  // something went wrong
  if (!$parliament) {
    return FALSE;
  }

  // run against all dates stored in parliament term
  $parliament_is_valid = FALSE;
  foreach ($parliament->field_parliament_valid[LANGUAGE_NONE] as $date_parliament_valid) {
    $has_no_end_date = $date_parliament_valid['value'] == $date_parliament_valid['value2'];
    $parliament_is_valid = strtotime($date_parliament_valid['value']) < time() &&
      (strtotime($date_parliament_valid['value2']) > time() ||
        $has_no_end_date);
    if ($parliament_is_valid) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Custom: Retrieve user depending on user or archived user is viewed.
 */
function _pw_get_current_user() {
  $user = &drupal_static(__FUNCTION__);
  if (!isset($user)) {
    switch (arg(0)) {
      // load by archived user profile
      case 'profile':
        $user = user_load_by_name(arg(1));
        $user_id = $user->uid;
        $vid = arg(3);
        $user = user_revision_load($user_id, $vid);
        break;

      // load by user profile
      case 'user':
        $user = menu_get_object('user');
        break;
      default:
        $user = FALSE;
    }
  }
  return $user;
}

/**
 * Custom: Retrieve parliament tag from node by nid.
 */
function _pw_get_parliament_term_tid_by_nid($nid) {

  $selected_node = node_load($nid);
  $node_type = $selected_node->type;

  switch ($node_type) {

    case 'sidejob':
      $tid = $selected_node->field_parliament[LANGUAGE_NONE][0]['tid'];
      return $tid;
      break;

    case 'committee_membership':
      $tid = $selected_node->field_parliament[LANGUAGE_NONE][0]['tid'];
      return $tid;
      break;

    case 'speech':
      $tid = $selected_node->field_parliament[LANGUAGE_NONE][0]['tid'];
      return $tid;
      break;
  }
  return FALSE;
}

/**
 * Custom: Send Debug Mail.
 */
function _pw_send_debug_mail($subject, $body){
  mail('debug@abgeordnetenwatch.de', $subject, $body."\n\n############################\n\n".print_r(debug_backtrace(), 1));
}
