<?php

/*
 * Implements hook_migrate_api(), setting the API level to 2, for
 * constituency migration classes to be recognized by the Migrate module.
 */
function migrate_constituency_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'ConstituencyTerm' => array(
        'class_name' => 'ConstituencyTermMigration',
        'group_name' => 'constituency',
      ),
    ),
  );
  return $api;
}

/**
 * Implements hook_update_projects_alter().
 */
function migrate_constituency_update_projects_alter(&$projects) {
  unset($projects['migrate_constituency']);
}
